services:
  alpine-postgres:
    image: postgres:17.5
    container_name: alpine-postgres
    restart: always
    shm_size: 1g
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alpine
    ports:
      - '55001:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0
    container_name: alpine-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/redis/data

volumes:
  postgres_data:
  redis-data:
